---
- name: Configurar ToDo en Ubuntu
  hosts: server2
  become: true
  remote_user: sysadmin

  tasks:

  - name: Copiar archivo WAR de la aplicación todo
    ansible.builtin.copy:
      src: /home/sysadmin/Downloads/todo.war
      dest: /opt/tomcat/webapps/todo.war
      owner: tomcat
      group: tomcat
      mode: '0644'

  - name: Reiniciar Tomcat
    ansible.builtin.systemd:
      name: tomcat
      state: restarted

