---
- name: Instalar Tomcat
  hosts: tomcat_servers
  become: true
  
tasks:
   
    - name: Instalar Java 
      ansible.builtin.package:
        name: java-11-openjdk-devel
        state: present

    - name: Descargar Tomcat
      get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.54/bin/apache-tomcat-9.0.54.tar.gz"
        dest: /opt/tomcat
   
    - name: Extraer Tomcat
      unarchive:
        src: /opt/apache-tomcat-9.0.54.tar.gz
        dest: /opt/tomcat
        remote_src: true

    #crear link simbólico a /opt/tomcat
    #crear directorio /opt/tomcat
    - name: Configurar archivo de propiedades de la aplicación
      template: templates/index.j2
        src: templates/app.properties.j2
        dest: /opt/tomcat/app.properties
        owner: root
        group: root
        mode: 0644

    - name: Habilitamos el servicio Tomcat en Systemd
      ansible.builtin.systemd:
        name: tomcat
        state: started
        enabled: true
 
    - name: Abrir los puertos en el Firewall para el Tomcat
      ansible.posix.firewalld:
        port: 8080  
        permanent: true
        state: enabled
