---
- name: Configuro el firewall para Mariadb
  hosts: server2
  become: true
  remote_user: sysadmin

  tasks:

    - name: UFW instalado
      ansible.builtin.apt:
        name: ufw
        state: present

    - name: Permitir puerto 22 en ufw
      ansible.builtin.ufw:
        rule: allow
        port: '22'

    - name: Defino politicas de tráfico saliente
      ansible.builtin.ufw:
        default: allow
        direction: outgoing

    - name: Defino politicas de tráfico entrante
      ansible.builtin.ufw:
        default: allow
        direction: incoming

    - name: servicio UFW levantado y activo
      ansible.builtin.ufw:
        state: enabled

    - name: MariaDB instalado
      ansible.builtin.apt:
        name: mariadb-server
        state: present

    - name: Instalar PyMySQL para soporte MySQL/MariaDB en Python
      ansible.builtin.apt:
        name: python3-pymysql
        state: present
    - name: Cambiar la configuracion para escuchar en todas las interfaces
      ansible.builtin.lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
      notify: Restart MariaDB

    - name: Habilitamos en ufw la conexión a mariadb
      ansible.builtin.ufw:
        rule: allow
        port: '3306'

    - name: Creo la base de datos todo
      ansible.builtin.mysql_db:
        login_user: root
        login_password: your_root_password
        name: todo
        state: present

  handlers:

    - name: Restart MariaDB
      ansible.builtin.systemd:
        name: mariadb
        state: restarted
